# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71d8f7d1ff4ee4d78fb7f179963cde4ecc6201095a8d04a7a3b2ae7dff0364026261075ba7e122d692134a000f6c8200b911ffd5b5276d06dbf9d89e12379813

test:
  secret_key_base: 201865c82283267a7decdd496799e9a11c6cebb0d6a6259691e9de91da51d3cfa81c4b5f997d77669cb03215a03bc5e09f556bc071981372b3d2cf278524b2aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
